source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://sources.aka-labs.com/scm/git/cocoapods'

use_frameworks!

platform :ios, '8.0'
pod 'AKAControls', :path => '..'
pod 'AKACommons', :path => '..'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
#pod 'AKAControls', '~> 0.0.6'

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end