//
//  AKAControlsStyleKit.m
//  AKAControls
//
//  Created by Michael Utech on 10.04.15.
//  Copyright (c) 2015 Gripsware GmbH. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "AKAControlsStyleKit.h"


@implementation AKAControlsStyleKit

#pragma mark Cache

static UIColor* _barButtonItemForegroundColor = nil;

static UIImage* _imageOfBackBarButtonItemIcon = nil;
static UIImage* _imageOfForthBarButtonItemIcon = nil;
static UIImage* _imageOfCloseKeyboardBarButtonItemIcon = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _barButtonItemForegroundColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)barButtonItemForegroundColor { return _barButtonItemForegroundColor; }

#pragma mark Drawing Methods

+ (void)drawBackBarButtonItemIcon
{

    //// Variable Declarations
    CGFloat barButtonItemStrokeWidth = 2;

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(26, 14)];
    [bezierPath addLineToPoint: CGPointMake(18, 21.77f)];
    [bezierPath addLineToPoint: CGPointMake(26, 30)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setStroke];
    bezierPath.lineWidth = barButtonItemStrokeWidth;
    [bezierPath stroke];
}

+ (void)drawForthBarButtonItemIcon
{

    //// Variable Declarations
    CGFloat barButtonItemStrokeWidth = 2;

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(18, 14)];
    [bezierPath addLineToPoint: CGPointMake(26, 21.77f)];
    [bezierPath addLineToPoint: CGPointMake(18, 30)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setStroke];
    bezierPath.lineWidth = barButtonItemStrokeWidth;
    [bezierPath stroke];
}

+ (void)drawCloseKeyboardBarButtonItemIcon
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(13, 14, 19, 12) cornerRadius: 1];
    [AKAControlsStyleKit.barButtonItemForegroundColor setStroke];
    rectanglePath.lineWidth = 1;
    [rectanglePath stroke];


    //// Bezier Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 26.98f, 30.63f);
    CGContextRotateCTM(context, 91.71f * (CGFloat)M_PI / 180);

    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(-0, -0)];
    [bezierPath addLineToPoint: CGPointMake(5, 4.58f)];
    [bezierPath addLineToPoint: CGPointMake(-0, 9.42f)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setStroke];
    bezierPath.lineWidth = 1;
    [bezierPath stroke];

    CGContextRestoreGState(context);


    //// Rectangle 3 Drawing
    UIBezierPath* rectangle3Path = [UIBezierPath bezierPathWithRect: CGRectMake(15.5, 17, 2, 2)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setFill];
    [rectangle3Path fill];


    //// Rectangle 4 Drawing
    UIBezierPath* rectangle4Path = [UIBezierPath bezierPathWithRect: CGRectMake(18.5, 17, 2, 2)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setFill];
    [rectangle4Path fill];


    //// Rectangle 6 Drawing
    UIBezierPath* rectangle6Path = [UIBezierPath bezierPathWithRect: CGRectMake(24.5, 17, 2, 2)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setFill];
    [rectangle6Path fill];


    //// Rectangle 7 Drawing
    UIBezierPath* rectangle7Path = [UIBezierPath bezierPathWithRect: CGRectMake(27.5, 17, 2, 2)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setFill];
    [rectangle7Path fill];


    //// Rectangle 9 Drawing
    UIBezierPath* rectangle9Path = [UIBezierPath bezierPathWithRect: CGRectMake(15.5, 21, 2, 2)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setFill];
    [rectangle9Path fill];


    //// Rectangle 10 Drawing
    UIBezierPath* rectangle10Path = [UIBezierPath bezierPathWithRect: CGRectMake(18.5, 21, 2, 2)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setFill];
    [rectangle10Path fill];


    //// Rectangle 12 Drawing
    UIBezierPath* rectangle12Path = [UIBezierPath bezierPathWithRect: CGRectMake(24.5, 21, 2, 2)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setFill];
    [rectangle12Path fill];


    //// Rectangle 13 Drawing
    UIBezierPath* rectangle13Path = [UIBezierPath bezierPathWithRect: CGRectMake(27.5, 21, 2, 2)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setFill];
    [rectangle13Path fill];


    //// Rectangle 2 Drawing
    UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(21.5, 17, 2, 2)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setFill];
    [rectangle2Path fill];


    //// Rectangle 5 Drawing
    UIBezierPath* rectangle5Path = [UIBezierPath bezierPathWithRect: CGRectMake(21.5, 21, 2, 2)];
    [AKAControlsStyleKit.barButtonItemForegroundColor setFill];
    [rectangle5Path fill];
}

#pragma mark Generated Images

+ (UIImage*)imageOfBackBarButtonItemIcon
{
    if (_imageOfBackBarButtonItemIcon)
        return _imageOfBackBarButtonItemIcon;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(44, 44), NO, 0.0f);
    [AKAControlsStyleKit drawBackBarButtonItemIcon];

    _imageOfBackBarButtonItemIcon = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfBackBarButtonItemIcon;
}

+ (UIImage*)imageOfForthBarButtonItemIcon
{
    if (_imageOfForthBarButtonItemIcon)
        return _imageOfForthBarButtonItemIcon;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(44, 44), NO, 0.0f);
    [AKAControlsStyleKit drawForthBarButtonItemIcon];

    _imageOfForthBarButtonItemIcon = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfForthBarButtonItemIcon;
}

+ (UIImage*)imageOfCloseKeyboardBarButtonItemIcon
{
    if (_imageOfCloseKeyboardBarButtonItemIcon)
        return _imageOfCloseKeyboardBarButtonItemIcon;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(44, 44), NO, 0.0f);
    [AKAControlsStyleKit drawCloseKeyboardBarButtonItemIcon];

    _imageOfCloseKeyboardBarButtonItemIcon = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfCloseKeyboardBarButtonItemIcon;
}

#pragma mark Customization Infrastructure

- (void)setBackBarButtonItemIconTargets: (NSArray*)backBarButtonItemIconTargets
{
    _backBarButtonItemIconTargets = backBarButtonItemIconTargets;

    for (id target in self.backBarButtonItemIconTargets)
        [target setImage:AKAControlsStyleKit.imageOfBackBarButtonItemIcon.CIImage];
}

- (void)setForthBarButtonItemIconTargets: (NSArray*)forthBarButtonItemIconTargets
{
    _forthBarButtonItemIconTargets = forthBarButtonItemIconTargets;

    for (id target in self.forthBarButtonItemIconTargets)
        [target setImage:AKAControlsStyleKit.imageOfForthBarButtonItemIcon.CIImage];
}

- (void)setCloseKeyboardBarButtonItemIconTargets: (NSArray*)closeKeyboardBarButtonItemIconTargets
{
    _closeKeyboardBarButtonItemIconTargets = closeKeyboardBarButtonItemIconTargets;

    for (id target in self.closeKeyboardBarButtonItemIconTargets)
        [target setImage:AKAControlsStyleKit.imageOfCloseKeyboardBarButtonItemIcon.CIImage];
}


@end
