//
//  AKAControlsStyleKit.h
//  AKABeacon
//
//  Created by Michael Utech on 10.04.15.
//  Copyright (c) 2015 Gripsware GmbH. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface AKAControlsStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* backBarButtonItemIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* forthBarButtonItemIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* closeKeyboardBarButtonItemIconTargets;

// Colors
+ (UIColor*)barButtonItemForegroundColor;

// Drawing Methods
+ (void)drawBackBarButtonItemIcon;
+ (void)drawForthBarButtonItemIcon;
+ (void)drawCloseKeyboardBarButtonItemIcon;

// Generated Images
+ (UIImage*)imageOfBackBarButtonItemIcon;
+ (UIImage*)imageOfForthBarButtonItemIcon;
+ (UIImage*)imageOfCloseKeyboardBarButtonItemIcon;

@end
