# This podfile is used for development and assumes that aka-ios-commons and aka-ios-beacon are
# checked out side-by-side.

source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'AKABeaconDemo.xcworkspace'
xcodeproj 'AKABeaconDemo.xcodeproj'

use_frameworks!

platform :ios, '8.2'

pod 'AKABeacon', '~> 0.1.2'
