# This podfile is used for development and assumes that aka-ios-commons and aka-ios-beacon are
# checked out side-by-side.

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.2'

workspace 'AKABeaconDemo.xcworkspace'
xcodeproj 'AKABeaconDemo.xcodeproj' # Will be renamed to project once we drop support for Cocoapods < 1.0

target 'AKABeaconDemo' do
	pod 'AKABeacon', '~> 0.3.1'
end
