source 'https://sources.aka-labs.com/scm/git/cocoapods'
source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'AKAControls.xcworkspace'
xcodeproj 'AKAControls.xcodeproj'
xcodeproj 'AKAControlsGallery.xcodeproj'

use_frameworks!

platform :ios, '8.0'

target :AKAControls, :exclusive => true do
    pod 'AKACommons', :path => '..'
    target :AKAControlsTests, :exclusive => true do
        xcodeproj 'AKAControls.xcodeproj'
    end
    xcodeproj 'AKAControls.xcodeproj'
end


target :AKAControlsGallery, :exclusive => true do
    pod 'AKAControls', :path => '..'
    pod 'AKACommons', :path => '..'
    #target :AKAControlsGalleryUITests do
    #    xcodeproj 'AKAControlsGallery.xcodeproj'
    #end
    xcodeproj 'AKAControlsGallery.xcodeproj'
end



