source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://sources.aka-labs.com/scm/git/cocoapods'
workspace 'AKAControls.xcworkspace'
xcodeproj 'AKAControls.xcodeproj'
use_frameworks!

platform :ios, '8.0'

target :AKAControls do
end

target :AKAControlsTests do
end

#pod 'AKACommons'
pod 'AKACommons', :path => '..'
